In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/drive/MyDrive/AI/Data Analysis/student/students_exans.csv")
df.head()

   gender  math score  reading score  writing score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75

In [4]:
for index, row in df.iterrows():
    print(index, row)

0 gender           female
math score           72
reading score        72
writing score        74
Name: 0, dtype: object
1 gender           female
math score           69
reading score        90
writing score        88
Name: 1, dtype: object
2 gender           female
math score           90
reading score        95
writing score        93
Name: 2, dtype: object
3 gender           male
math score         47
reading score      57
writing score      44
Name: 3, dtype: object
4 gender           male
math score         76
reading score      78
writing score      75
Name: 4, dtype: object
5 gender           female
math score           71
reading score        83
writing score        78
Name: 5, dtype: object
6 gender           female
math score           88
reading score        95
writing score        92
Name: 6, dtype: object
7 gender           male
math score         40
reading score      43
writing score      39
Name: 7, dtype: object
8 gender           male
math score         64
reading score      64
writing score      67
Name: 8, dtype: object
9 gender           female
math score           38
reading score        60
writing score        50
Name: 9, dtype: object
10 gender           male
math score         58
reading score      54
writing score      52
Name: 10, dtype: object
11 gender           male
math score         40
reading score      52
writing score      43
Name: 11, dtype: object
12 gender           female
math score           65
reading score        81
writing score        73
Name: 12, dtype: object
13 gender           male
math score         78
reading score      72
writing score      70
Name: 13, dtype: object
14 gender           female
math score           50
reading score        53
writing score        58
Name: 14, dtype: object
15 gender           female
math score           69
reading score        75
writing score        78
Name: 15, dtype: object
16 gender           male
math score         88
reading score      89
writing score      86
Name: 16, dtype: object
17 gender           female
math score           18
reading score        32
writing score        28
Name: 17, dtype: object
18 gender           male
math score         46
reading score      42
writing score      46
Name: 18, dtype: object
19 gender           female
math score           54
reading score        58
writing score        61
Name: 19, dtype: object
20 gender           male
math score         66
reading score      69
writing score      63
Name: 20, dtype: object
21 gender           female
math score           65
reading score        75
writing score        70
Name: 21, dtype: object
22 gender           male
math score         44
reading score      54
writing score      53
Name: 22, dtype: object
23 gender           female
math score           69
reading score        73
writing score        73
Name: 23, dtype: object
24 gender           male
math score         74
reading score      71
writing score      80
Name: 24, dtype: object
25 gender           male
math score         73
reading score      74
writing score      72
Name: 25, dtype: object
26 gender           male
math score         69
reading score      54
writing score      55
Name: 26, dtype: object
27 gender           female
math score           67
reading score        69
writing score        75
Name: 27, dtype: object
28 gender           male
math score         70
reading score      70
writing score      65
Name: 28, dtype: object
29 gender           female
math score           62
reading score        70
writing score        75
Name: 29, dtype: object
30 gender           female
math score           69
reading score        74
writing score        74
Name: 30, dtype: object
31 gender           female
math score           63
reading score        65
writing score        61
Name: 31, dtype: object
32 gender           female
math score           56
reading score        72
writing score        65
Name: 32, dtype: object
33 gender           male
math score         40
reading score      42
writing score      38
Name: 33, dtype: object
34 gender           male
math score         97
reading score      87
writing score      82
Name: 34, dtype: object
35 gender           male
math score         81
reading score      81
writing score      79
Name: 35, dtype: object
36 gender           female
math score           74
reading score        81
writing score        83
Name: 36, dtype: object
37 gender           female
math score           50
reading score        64
writing score        59
Name: 37, dtype: object
38 gender           female
math score           75
reading score        90
writing score        88
Name: 38, dtype: object
39 gender           male
math score         57
reading score      56
writing score      57
Name: 39, dtype: object
40 gender           male
math score         55
reading score      61
writing score      54
Name: 40, dtype: object
41 gender           female
math score           58
reading score        73
writing score        68
Name: 41, dtype: object
42 gender           female
math score           53
reading score        58
writing score        65
Name: 42, dtype: object
43 gender           male
math score         59
reading score      65
writing score      66
Name: 43, dtype: object
44 gender           female
math score           50
reading score        56
writing score        54
Name: 44, dtype: object
45 gender           male
math score         65
reading score      54
writing score      57
Name: 45, dtype: object
46 gender           female
math score           55
reading score        65
writing score        62
Name: 46, dtype: object
47 gender           female
math score           66
reading score        71
writing score        76
Name: 47, dtype: object
48 gender           female
math score           57
reading score        74
writing score        76
Name: 48, dtype: object
49 gender           male
math score         82
reading score      84
writing score      82
Name: 49, dtype: object
50 gender           male
math score         53
reading score      55
writing score      48
Name: 50, dtype: object
51 gender           male
math score         77
reading score      69
writing score      68
Name: 51, dtype: object
52 gender           male
math score         53
reading score      44
writing score      42
Name: 52, dtype: object
53 gender           male
math score         88
reading score      78
writing score      75
Name: 53, dtype: object
54 gender           female
math score           71
reading score        84
writing score        87
Name: 54, dtype: object
55 gender           female
math score           33
reading score        41
writing score        43
Name: 55, dtype: object
56 gender           female
math score           82
reading score        85
writing score        86
Name: 56, dtype: object
57 gender           male
math score         52
reading score      55
writing score      49
Name: 57, dtype: object
58 gender           male
math score         58
reading score      59
writing score      58
Name: 58, dtype: object
59 gender           female
math score            0
reading score        17
writing score        10
Name: 59, dtype: object
60 gender           male
math score         79
reading score      74
writing score      72
Name: 60, dtype: object
61 gender           male
math score         39
reading score      39
writing score      34
Name: 61, dtype: object
62 gender           male
math score         62
reading score      61
writing score      55
Name: 62, dtype: object
63 gender           female
math score           69
reading score        80
writing score        71
Name: 63, dtype: object
64 gender           female
math score           59
reading score        58
writing score        59
Name: 64, dtype: object
65 gender           male
math score         67
reading score      64
writing score      61
Name: 65, dtype: object
66 gender           male
math score         45
reading score      37
writing score      37
Name: 66, dtype: object
67 gender           female
math score           60
reading score        72
writing score        74
Name: 67, dtype: object
68 gender           male
math score         61
reading score      58
writing score      56
Name: 68, dtype: object
69 gender           female
math score           39
reading score        64
writing score        57
Name: 69, dtype: object
70 gender           female
math score           58
reading score        63
writing score        73
Name: 70, dtype: object
71 gender           male
math score         63
reading score      55
writing score      63
Name: 71, dtype: object
72 gender           female
math score           41
reading score        51
writing score        48
Name: 72, dtype: object
73 gender           male
math score         61
reading score      57
writing score      56
Name: 73, dtype: object
74 gender           male
math score         49
reading score      49
writing score      41
Name: 74, dtype: object
75 gender           male
math score         44
reading score      41
writing score      38
Name: 75, dtype: object
76 gender           male
math score         30
reading score      26
writing score      22
Name: 76, dtype: object
77 gender           male
math score         80
reading score      78
writing score      81
Name: 77, dtype: object
78 gender           female
math score           61
reading score        74
writing score        72
Name: 78, dtype: object
79 gender           female
math score           62
reading score        68
writing score        68
Name: 79, dtype: object
80 gender           female
math score           47
reading score        49
writing score        50
Name: 80, dtype: object
81 gender           male
math score         49
reading score      45
writing score      45
Name: 81, dtype: object
82 gender           male
math score         50
reading score      47
writing score      54
Name: 82, dtype: object
83 gender           male
math score         72
reading score      64
writing score      63
Name: 83, dtype: object
84 gender           male
math score         42
reading score      39
writing score      34
Name: 84, dtype: object
85 gender           female
math score           73
reading score        80
writing score        82
Name: 85, dtype: object
86 gender           female
math score           76
reading score        83
writing score        88
Name: 86, dtype: object
87 gender           female
math score           71
reading score        71
writing score        74
Name: 87, dtype: object
88 gender           female
math score           58
reading score        70
writing score        67
Name: 88, dtype: object
89 gender           female
math score           73
reading score        86
writing score        82
Name: 89, dtype: object
90 gender           female
math score           65
reading score        72
writing score        74
Name: 90, dtype: object
91 gender           male
math score         27
reading score      34
writing score      36
Name: 91, dtype: object
92 gender           male
math score         71
reading score      79
writing score      71
Name: 92, dtype: object
93 gender           male
math score         43
reading score      45
writing score      50
Name: 93, dtype: object
94 gender           female
math score           79
reading score        86
writing score        92
Name: 94, dtype: object
95 gender           male
math score         78
reading score      81
writing score      82
Name: 95, dtype: object
96 gender           male
math score         65
reading score      66
writing score      62
Name: 96, dtype: object
97 gender           female
math score           63
reading score        72
writing score        70
Name: 97, dtype: object
98 gender           female
math score           58
reading score        67
writing score        62
Name: 98, dtype: object
99 gender           female
math score           65
reading score        67
writing score        62
Name: 99, dtype: object
100 gender           male
math score         79
reading score      67
writing score      67
Name: 100, dtype: object
101 gender           male
math score         68
reading score      74
writing score      74
Name: 101, dtype: object
102 gender           female
math score           85
reading score        91
writing score        89
Name: 102, dtype: object
103 gender           male
math score         60
reading score      44
writing score      47
Name: 103, dtype: object
104 gender           male
math score         98
reading score      86
writing score      90
Name: 104, dtype: object
105 gender           female
math score           58
reading score        67
writing score        72
Name: 105, dtype: object
106 gender           female
math score           87
reading score       100
writing score       100
Name: 106, dtype: object
107 gender           male
math score         66
reading score      63
writing score      64
Name: 107, dtype: object
108 gender           female
math score           52
reading score        76
writing score        70
Name: 108, dtype: object
109 gender           female
math score           70
reading score        64
writing score        72
Name: 109, dtype: object
110 gender           female
math score           77
reading score        89
writing score        98
Name: 110, dtype: object
111 gender           male
math score         62
reading score      55
writing score      49
Name: 111, dtype: object
112 gender           male
math score         54
reading score      53
writing score      47
Name: 112, dtype: object
113 gender           female
math score           51
reading score        58
writing score        54
Name: 113, dtype: object
114 gender           female
math score           99
reading score       100
writing score       100
Name: 114, dtype: object
115 gender           male
math score         84
reading score      77
writing score      74
Name: 115, dtype: object
116 gender           female
math score           75
reading score        85
writing score        82
Name: 116, dtype: object
117 gender           female
math score           78
reading score        82
writing score        79
Name: 117, dtype: object
118 gender           female
math score           51
reading score        63
writing score        61
Name: 118, dtype: object
119 gender           female
math score           55
reading score        69
writing score        65
Name: 119, dtype: object
120 gender           female
math score           79
reading score        92
writing score        89
Name: 120, dtype: object
121 gender           male
math score         91
reading score      89
writing score      92
Name: 121, dtype: object
122 gender           female
math score           88
reading score        93
writing score        93
Name: 122, dtype: object
123 gender           male
math score         63
reading score      57
writing score      56
Name: 123, dtype: object
124 gender           male
math score         83
reading score      80
writing score      73
Name: 124, dtype: object
125 gender           female
math score           87
reading score        95
writing score        86
Name: 125, dtype: object
126 gender           male
math score         72
reading score      68
writing score      67
Name: 126, dtype: object
127 gender           male
math score         65
reading score      77
writing score      74
Name: 127, dtype: object
128 gender           male
math score         82
reading score      82
writing score      74
Name: 128, dtype: object
129 gender           female
math score           51
reading score        49
writing score        51
Name: 129, dtype: object
130 gender           male
math score         89
reading score      84
writing score      82
Name: 130, dtype: object
131 gender           male
math score         53
reading score      37
writing score      40
Name: 131, dtype: object
132 gender           male
math score         87
reading score      74
writing score      70
Name: 132, dtype: object
133 gender           female
math score           75
reading score        81
writing score        84
Name: 133, dtype: object
134 gender           male
math score         74
reading score      79
writing score      75
Name: 134, dtype: object
135 gender           male
math score         58
reading score      55
writing score      48
Name: 135, dtype: object
136 gender           male
math score         51
reading score      54
writing score      41
Name: 136, dtype: object
137 gender           male
math score         70
reading score      55
writing score      56
Name: 137, dtype: object
138 gender           female
math score           59
reading score        66
writing score        67
Name: 138, dtype: object
139 gender           male
math score         71
reading score      61
writing score      69
Name: 139, dtype: object
140 gender           female
math score           76
reading score        72
writing score        71
Name: 140, dtype: object
141 gender           female
math score           59
reading score        62
writing score        64
Name: 141, dtype: object
142 gender           female
math score           42
reading score        55
writing score        54
Name: 142, dtype: object
143 gender           male
math score         57
reading score      43
writing score      47
Name: 143, dtype: object
144 gender           male
math score         88
reading score      73
writing score      78
Name: 144, dtype: object
145 gender           female
math score           22
reading score        39
writing score        33
Name: 145, dtype: object
146 gender           male
math score         88
reading score      84
writing score      75
Name: 146, dtype: object
147 gender           male
math score         73
reading score      68
writing score      66
Name: 147, dtype: object
148 gender           female
math score           68
reading score        75
writing score        81
Name: 148, dtype: object
149 gender           male
math score        100
reading score     100
writing score      93
Name: 149, dtype: object
150 gender           male
math score         62
reading score      67
writing score      69
Name: 150, dtype: object
151 gender           male
math score         77
reading score      67
writing score      68
Name: 151, dtype: object
152 gender           female
math score           59
reading score        70
writing score        66
Name: 152, dtype: object
153 gender           male
math score         54
reading score      49
writing score      47
Name: 153, dtype: object
154 gender           male
math score         62
reading score      67
writing score      61
Name: 154, dtype: object
155 gender           female
math score           70
reading score        89
writing score        88
Name: 155, dtype: object
156 gender           female
math score           66
reading score        74
writing score        78
Name: 156, dtype: object
157 gender           male
math score         60
reading score      60
writing score      60
Name: 157, dtype: object
158 gender           female
math score           61
reading score        86
writing score        87
Name: 158, dtype: object
159 gender           male
math score         66
reading score      62
writing score      64
Name: 159, dtype: object
160 gender           male
math score         82
reading score      78
writing score      74
Name: 160, dtype: object
161 gender           female
math score           75
reading score        88
writing score        85
Name: 161, dtype: object
162 gender           male
math score         49
reading score      53
writing score      52
Name: 162, dtype: object
163 gender           male
math score         52
reading score      53
writing score      49
Name: 163, dtype: object
164 gender           female
math score           81
reading score        92
writing score        91
Name: 164, dtype: object
165 gender           female
math score           96
reading score       100
writing score       100
Name: 165, dtype: object
166 gender           male
math score         53
reading score      51
writing score      51
Name: 166, dtype: object
167 gender           female

In [5]:
for index, row in df.iterrows():
    print(index, row['gender'], row['math score'])

0 female 72
1 female 69
2 female 90
3 male 47
4 male 76
5 female 71
6 female 88
7 male 40
8 male 64
9 female 38
10 male 58
11 male 40
12 female 65
13 male 78
14 female 50
15 female 69
16 male 88
17 female 18
18 male 46
19 female 54
20 male 66
21 female 65
22 male 44
23 female 69
24 male 74
25 male 73
26 male 69
27 female 67
28 male 70
29 female 62
30 female 69
31 female 63
32 female 56
33 male 40
34 male 97
35 male 81
36 female 74
37 female 50
38 female 75
39 male 57
40 male 55
41 female 58
42 female 53
43 male 59
44 female 50
45 male 65
46 female 55
47 female 66
48 female 57
49 male 82
50 male 53
51 male 77
52 male 53
53 male 88
54 female 71
55 female 33
56 female 82
57 male 52
58 male 58
59 female 0
60 male 79
61 male 39
62 male 62
63 female 69
64 female 59
65 male 67
66 male 45
67 female 60
68 male 61
69 female 39
70 female 58
71 male 63
72 female 41
73 male 61
74 male 49
75 male 44
76 male 30
77 male 80
78 female 61
79 female 62
80 female 47
81 male 49
82 male 50
83 male 72
84 male 42
85 female 73
86 female 76
87 female 71
88 female 58
89 female 73
90 female 65
91 male 27
92 male 71
93 male 43
94 female 79
95 male 78
96 male 65
97 female 63
98 female 58
99 female 65
100 male 79
101 male 68
102 female 85
103 male 60
104 male 98
105 female 58
106 female 87
107 male 66
108 female 52
109 female 70
110 female 77
111 male 62
112 male 54
113 female 51
114 female 99
115 male 84
116 female 75
117 female 78
118 female 51
119 female 55
120 female 79
121 male 91
122 female 88
123 male 63
124 male 83
125 female 87
126 male 72
127 male 65
128 male 82
129 female 51
130 male 89
131 male 53
132 male 87
133 female 75
134 male 74
135 male 58
136 male 51
137 male 70
138 female 59
139 male 71
140 female 76
141 female 59
142 female 42
143 male 57
144 male 88
145 female 22
146 male 88
147 male 73
148 female 68
149 male 100
150 male 62
151 male 77
152 female 59
153 male 54
154 male 62
155 female 70
156 female 66
157 male 60
158 female 61
159 male 66
160 male 82
161 female 75
162 male 49
163 male 52
164 female 81
165 female 96
166 male 53
167 female 58
168 female 68
169 female 67
170 male 72
171 male 94
172 female 79
173 female 63
174 female 43
175 female 81
176 female 46
177 female 71
178 female 52
179 female 97
180 male 62
181 female 46
182 female 50
183 female 65
184 male 45
185 male 65
186 male 80
187 male 62
188 male 48
189 female 77
190 female 66
191 male 76
192 female 62
193 male 77
194 female 69
195 male 61
196 male 59
197 male 55
198 female 45
199 female 78
200 female 67
201 female 65
202 male 69
203 female 57
204 male 59
205 male 74
206 male 82
207 male 81
208 female 74
209 female 58
210 male 80
211 male 35
212 female 42
213 male 60
214 male 87
215 male 84
216 female 83
217 female 34
218 male 66
219 male 61
220 female 56
221 male 87
222 female 55
223 male 86
224 female 52
225 female 45
226 female 72
227 male 57
228 male 68
229 female 88
230 male 76
231 male 46
232 female 67
233 male 92
234 male 83
235 male 80
236 male 63
237 female 64
238 male 54
239 male 84
240 male 73
241 female 80
242 female 56
243 male 59
244 male 75
245 male 85
246 male 89
247 female 58
248 female 65
249 male 68
250 male 47
251 female 71
252 female 60
253 male 80
254 male 54
255 female 62
256 female 64
257 male 78
258 female 70
259 female 65
260 female 64
261 male 79
262 female 44
263 female 99
264 male 76
265 male 59
266 female 63
267 female 69
268 female 88
269 female 71
270 male 69
271 male 58
272 female 47
273 female 65
274 male 88
275 male 83
276 female 85
277 female 59
278 female 65
279 male 73
280 male 53
281 male 45
282 female 73
283 female 70
284 female 37
285 male 81
286 male 97
287 female 67
288 male 88
289 male 77
290 male 76
291 male 86
292 male 63
293 female 65
294 male 78
295 male 67
296 male 46
297 male 71
298 male 40
299 male 90
300 male 81
301 male 56
302 female 67
303 male 80
304 female 74
305 male 69
306 male 99
307 male 51
308 female 53
309 female 49
310 female 73
311 male 66
312 male 67
313 female 68
314 female 59
315 male 71
316 female 77
317 male 83
318 male 63
319 female 56
320 female 67
321 female 75
322 female 71
323 female 43
324 female 41
325 female 82
326 male 61
327 male 28
328 male 82
329 female 41
330 male 71
331 male 47
332 male 62
333 male 90
334 female 83
335 female 61
336 male 76
337 male 49
338 female 24
339 female 35
340 male 58
341 female 61
342 female 69
343 male 67
344 male 79
345 female 72
346 male 62
347 female 77
348 male 75
349 male 87
350 female 52
351 male 66
352 female 63
353 female 46
354 female 59
355 female 61
356 male 63
357 female 42
358 male 59
359 female 80
360 female 58
361 male 85
362 female 52
363 female 27
364 male 59
365 male 49
366 male 69
367 male 61
368 female 44
369 female 73
370 male 84
371 female 45
372 male 74
373 female 82
374 female 59
375 male 46
376 female 80
377 female 85
378 female 71
379 male 66
380 female 80
381 male 87
382 male 79
383 female 38
384 female 38
385 female 67
386 female 64
387 female 57
388 female 62
389 male 73
390 male 73
391 female 77
392 male 76
393 male 57
394 female 65
395 male 48
396 female 50
397 female 85
398 male 74
399 male 60
400 female 59
401 male 53
402 female 49
403 female 88
404 female 54
405 female 63
406 male 65
407 female 82
408 female 52
409 male 87
410 female 70
411 male 84
412 male 71
413 male 63
414 female 51
415 male 84
416 male 71
417 male 74
418 male 68
419 male 57
420 female 82
421 female 57
422 female 47
423 female 59
424 male 41
425 female 62
426 male 86
427 male 69
428 male 65
429 male 68
430 male 64
431 female 61
432 male 61
433 female 47
434 male 73
435 male 50
436 male 75
437 male 75
438 male 70
439 male 89
440 female 67
441 female 78
442 female 59
443 female 73
444 male 79
445 female 67
446 male 69
447 male 86
448 male 47
449 male 81
450 female 64
451 female 100
452 female 65
453 male 65
454 female 53
455 male 37
456 female 79
457 male 53
458 female 100
459 male 72
460 male 53
461 male 54
462 female 71
463 female 77
464 male 75
465 female 84
466 female 26
467 male 72
468 female 77
469 male 91
470 female 83
471 female 63
472 female 68
473 female 59
474 female 90
475 female 71
476 male 76
477 male 80
478 female 55
479 male 76
480 male 73
481 female 52
482 male 68
483 male 59
484 female 49
485 male 70
486 male 61
487 female 60
488 male 64
489 male 79
490 female 65
491 female 64
492 female 83
493 female 81
494 female 54
495 male 68
496 female 54
497 female 59
498 female 66
499 male 76
500 female 74
501 female 94
502 male 63
503 female 95
504 female 40
505 female 82
506 male 68
507 male 55
508 male 79
509 female 86
510 male 76
511 male 64
512 male 62
513 female 54
514 female 77
515 female 76
516 female 74
517 female 66
518 female 66
519 female 67
520 male 71
521 female 91
522 male 69
523 male 54
524 male 53
525 male 68
526 male 56
527 female 36
528 female 29
529 female 62
530 female 68
531 female 47
532 male 62
533 female 79
534 male 73
535 female 66
536 male 51
537 female 51
538 male 85
539 male 97
540 male 75
541 male 79
542 female 81
543 female 82
544 female 64
545 male 78
546 female 92
547 male 72
548 female 62
549 male 79
550 male 79
551 male 87
552 female 40
553 male 77
554 male 53
555 female 32
556 female 55
557 male 61
558 female 53
559 male 73
560 female 74
561 female 63
562 male 96
563 female 63
564 male 48
565 male 48
566 female 92
567 female 61
568 male 63
569 male 68
570 male 71
571 male 91
572 female 53
573 female 50
574 female 74
575 male 40
576 male 61
577 female 81
578 female 48
579 female 53
580 female 81
581 female 77
582 female 63
583 female 73
584 female 69
585 female 65
586 female 55
587 female 44
588 female 54
589 female 48
590 male 58
591 male 71
592 male 68
593 female 74
594 female 92
595 female 56
596 male 30
597 male 53
598 female 69
599 female 65
600 female 54
601 female 29
602 female 76
603 male 60
604 male 84
605 male 75
606 female 85
607 female 40
608 female 61
609 female 58
610 male 69
611 female 58
612 male 94
613 female 65
614 female 82
615 female 60
616 female 37
617 male 88
618 male 95
619 male 65
620 female 35
621 male 62
622 male 58
623 male 100
624 female 61
625 male 100
626 male 69
627 male 61
628 male 49
629 female 44
630 male 67
631 male 79
632 female 66
633 female 75
634 male 84
635 male 71
636 female 67
637 female 80
638 male 86
639 female 76
640 male 41
641 female 74
642 female 72
643 female 74
644 male 70
645 female 65
646 female 59
647 female 64
648 female 50
649 female 69
650 male 51
651 female 68
652 female 85
653 female 65
654 female 73
655 female 62
656 male 77
657 male 69
658 female 43
659 male 90
660 male 74
661 male 73
662 female 55
663 female 65
664 male 80
665 female 50
666 female 63
667 female 77
668 male 73
669 male 81
670 female 66
671 male 52
672 female 69
673 female 65
674 female 69
675 female 50
676 female 73
677 female 70
678 male 81
679 male 63
680 female 67
681 male 60
682 male 62
683 female 29
684 male 62
685 female 94
686 male 85
687 male 77
688 male 53
689 male 93
690 female 49
691 female 73
692 female 66
693 female 77
694 female 49
695 female 79
696 female 75
697 female 59
698 female 57
699 male 66
700 female 79
701 female 57
702 male 87
703 female 63
704 female 59
705 male 62
706 male 46
707 male 66
708 male 89
709 female 42
710 male 93
711 female 80
712 female 98
713 male 81
714 female 60
715 female 76
716 male 73
717 female 96
718 female 76
719 male 91
720 female 62
721 male 55
722 female 74
723 male 50
724 male 47
725 male 81
726 female 65
727 male 68
728 female 73
729 male 53
730 female 68
731 male 55
732 female 87
733 male 55
734 female 53
735 male 67
736 male 92
737 female 53
738 male 81
739 male 61
740 male 80
741 female 37
742 female 81
743 female 59
744 male 55
745 male 72
746 male 69
747 male 69
748 female 50
749 male 87
750 male 71
751 male 68
752 male 79
753 female 77
754 male 58
755 female 84
756 male 55
757 male 70
758 female 52
759 male 69
760 female 53
761 female 48
762 male 78
763 female 62
764 male 60
765 female 74
766 female 58
767 male 76
768 female 68
769 male 58
770 male 52
771 male 75
772 female 52
773 female 62
774 male 66
775 female 49
776 female 66
777 female 35
778 female 72
779 male 94
780 female 46
781 female 77
782 female 76
783 female 52
784 male 91
785 female 32
786 female 72
787 female 19
788 male 68
789 female 52
790 female 48
791 female 60
792 male 66
793 male 89
794 female 42
795 female 57
796 male 70
797 female 70
798 male 69
799 female 52
800 male 67
801 male 76
802 female 87
803 female 82
804 female 73
805 male 75
806 female 64
807 female 41
808 male 90
809 male 59
810 male 51
811 male 45
812 female 54
813 male 87
814 female 72
815 male 94
816 female 45
817 male 61
818 female 60
819 female 77
820 female 85
821 female 78
822 male 49
823 female 71
824 female 48
825 male 62
826 female 56
827 female 65
828 female 69
829 male 68
830 female 61
831 female 74
832 male 64
833 female 77
834 male 58
835 female 60
836 male 73
837 female 75
838 male 58
839 female 66
840 female 39
841 male 64
842 female 23
843 male 74
844 female 40
845 male 90
846 male 91
847 male 64
848 female 59
849 male 80
850 male 71
851 female 61
852 female 87
853 male 82
854 male 62
855 female 97
856 male 75
857 female 65
858 male 52
859 male 87
860 female 53
861 female 81
862 male 39
863 female 71
864 male 97
865 male 82
866 male 59
867 male 61
868 male 78
869 male 49
870 male 59
871 female 70
872 male 82
873 male 90
874 female 43
875 male 80
876 male 81
877 male 57
878 female 59
879 female 64
880 male 63
881 female 71
882 female 64
883 male 55
884 female 51
885 female 62
886 female 93
887 male 54
888 female 69
889 male 44
890 female 86
891 female 85
892 female 50
893 male 88
894 female 59
895 female 32
896 male 36
897 female 63
898 male 67
899 female 65
900 male 85
901 female 73
902 female 34
903 female 93
904 female 67
905 male 88
906 male 57
907 female 79
908 female 67
909 male 70
910 male 50
911 female 69
912 female 52
913 female 47
914 female 46
915 female 68
916 male 100
917 female 44
918 female 57
919 male 91
920 male 69
921 female 35
922 male 72
923 female 54
924 male 74
925 male 74
926 male 64
927 female 65
928 male 46
929 female 48
930 male 67
931 male 62
932 male 61
933 male 70
934 male 98
935 male 70
936 male 67
937 female 57
938 male 85
939 male 77
940 male 72
941 female 78
942 male 81
943 male 61
944 female 58
945 female 54
946 male 82
947 female 49
948 male 49
949 female 57
950 male 94
951 female 75
952 female 74
953 male 58
954 female 62
955 male 72
956 male 84
957 female 92
958 female 45
959 male 75
960 female 56
961 female 48
962 female 100
963 female 65
964 male 72
965 female 62
966 male 66
967 male 63
968 female 68
969 female 75
970 female 89
971 male 78
972 female 53
973 female 49
974 female 54
975 female 64
976 male 60
977 male 62
978 male 55
979 female 91
980 female 8
981 male 81
982 male 79
983 female 78
984 female 74
985 male 57
986 female 40
987 male 81
988 female 44
989 female 67
990 male 86
991 female 65
992 female 55
993 female 62
994 male 63
995 female 88
996 male 62
997 female 59
998 female 68
999 female 77

In [6]:
for row in df.itertuples():
    print(row)

Pandas(Index=0, gender='female', _2=72, _3=72, _4=74)
Pandas(Index=1, gender='female', _2=69, _3=90, _4=88)
Pandas(Index=2, gender='female', _2=90, _3=95, _4=93)
Pandas(Index=3, gender='male', _2=47, _3=57, _4=44)
Pandas(Index=4, gender='male', _2=76, _3=78, _4=75)
Pandas(Index=5, gender='female', _2=71, _3=83, _4=78)
Pandas(Index=6, gender='female', _2=88, _3=95, _4=92)
Pandas(Index=7, gender='male', _2=40, _3=43, _4=39)
Pandas(Index=8, gender='male', _2=64, _3=64, _4=67)
Pandas(Index=9, gender='female', _2=38, _3=60, _4=50)
Pandas(Index=10, gender='male', _2=58, _3=54, _4=52)
Pandas(Index=11, gender='male', _2=40, _3=52, _4=43)
Pandas(Index=12, gender='female', _2=65, _3=81, _4=73)
Pandas(Index=13, gender='male', _2=78, _3=72, _4=70)
Pandas(Index=14, gender='female', _2=50, _3=53, _4=58)
Pandas(Index=15, gender='female', _2=69, _3=75, _4=78)
Pandas(Index=16, gender='male', _2=88, _3=89, _4=86)
Pandas(Index=17, gender='female', _2=18, _3=32, _4=28)
Pandas(Index=18, gender='male', _2=46, _3=42, _4=46)
Pandas(Index=19, gender='female', _2=54, _3=58, _4=61)
Pandas(Index=20, gender='male', _2=66, _3=69, _4=63)
Pandas(Index=21, gender='female', _2=65, _3=75, _4=70)
Pandas(Index=22, gender='male', _2=44, _3=54, _4=53)
Pandas(Index=23, gender='female', _2=69, _3=73, _4=73)
Pandas(Index=24, gender='male', _2=74, _3=71, _4=80)
Pandas(Index=25, gender='male', _2=73, _3=74, _4=72)
Pandas(Index=26, gender='male', _2=69, _3=54, _4=55)
Pandas(Index=27, gender='female', _2=67, _3=69, _4=75)
Pandas(Index=28, gender='male', _2=70, _3=70, _4=65)
Pandas(Index=29, gender='female', _2=62, _3=70, _4=75)
Pandas(Index=30, gender='female', _2=69, _3=74, _4=74)
Pandas(Index=31, gender='female', _2=63, _3=65, _4=61)
Pandas(Index=32, gender='female', _2=56, _3=72, _4=65)
Pandas(Index=33, gender='male', _2=40, _3=42, _4=38)
Pandas(Index=34, gender='male', _2=97, _3=87, _4=82)
Pandas(Index=35, gender='male', _2=81, _3=81, _4=79)
Pandas(Index=36, gender='female', _2=74, _3=81, _4=83)
Pandas(Index=37, gender='female', _2=50, _3=64, _4=59)
Pandas(Index=38, gender='female', _2=75, _3=90, _4=88)
Pandas(Index=39, gender='male', _2=57, _3=56, _4=57)
Pandas(Index=40, gender='male', _2=55, _3=61, _4=54)
Pandas(Index=41, gender='female', _2=58, _3=73, _4=68)
Pandas(Index=42, gender='female', _2=53, _3=58, _4=65)
Pandas(Index=43, gender='male', _2=59, _3=65, _4=66)
Pandas(Index=44, gender='female', _2=50, _3=56, _4=54)
Pandas(Index=45, gender='male', _2=65, _3=54, _4=57)
Pandas(Index=46, gender='female', _2=55, _3=65, _4=62)
Pandas(Index=47, gender='female', _2=66, _3=71, _4=76)
Pandas(Index=48, gender='female', _2=57, _3=74, _4=76)
Pandas(Index=49, gender='male', _2=82, _3=84, _4=82)
Pandas(Index=50, gender='male', _2=53, _3=55, _4=48)
Pandas(Index=51, gender='male', _2=77, _3=69, _4=68)
Pandas(Index=52, gender='male', _2=53, _3=44, _4=42)
Pandas(Index=53, gender='male', _2=88, _3=78, _4=75)
Pandas(Index=54, gender='female', _2=71, _3=84, _4=87)
Pandas(Index=55, gender='female', _2=33, _3=41, _4=43)
Pandas(Index=56, gender='female', _2=82, _3=85, _4=86)
Pandas(Index=57, gender='male', _2=52, _3=55, _4=49)
Pandas(Index=58, gender='male', _2=58, _3=59, _4=58)
Pandas(Index=59, gender='female', _2=0, _3=17, _4=10)
Pandas(Index=60, gender='male', _2=79, _3=74, _4=72)
Pandas(Index=61, gender='male', _2=39, _3=39, _4=34)
Pandas(Index=62, gender='male', _2=62, _3=61, _4=55)
Pandas(Index=63, gender='female', _2=69, _3=80, _4=71)
Pandas(Index=64, gender='female', _2=59, _3=58, _4=59)
Pandas(Index=65, gender='male', _2=67, _3=64, _4=61)
Pandas(Index=66, gender='male', _2=45, _3=37, _4=37)
Pandas(Index=67, gender='female', _2=60, _3=72, _4=74)
Pandas(Index=68, gender='male', _2=61, _3=58, _4=56)
Pandas(Index=69, gender='female', _2=39, _3=64, _4=57)
Pandas(Index=70, gender='female', _2=58, _3=63, _4=73)
Pandas(Index=71, gender='male', _2=63, _3=55, _4=63)
Pandas(Index=72, gender='female', _2=41, _3=51, _4=48)
Pandas(Index=73, gender='male', _2=61, _3=57, _4=56)
Pandas(Index=74, gender='male', _2=49, _3=49, _4=41)
Pandas(Index=75, gender='male', _2=44, _3=41, _4=38)
Pandas(Index=76, gender='male', _2=30, _3=26, _4=22)
Pandas(Index=77, gender='male', _2=80, _3=78, _4=81)
Pandas(Index=78, gender='female', _2=61, _3=74, _4=72)
Pandas(Index=79, gender='female', _2=62, _3=68, _4=68)
Pandas(Index=80, gender='female', _2=47, _3=49, _4=50)
Pandas(Index=81, gender='male', _2=49, _3=45, _4=45)
Pandas(Index=82, gender='male', _2=50, _3=47, _4=54)
Pandas(Index=83, gender='male', _2=72, _3=64, _4=63)
Pandas(Index=84, gender='male', _2=42, _3=39, _4=34)
Pandas(Index=85, gender='female', _2=73, _3=80, _4=82)
Pandas(Index=86, gender='female', _2=76, _3=83, _4=88)
Pandas(Index=87, gender='female', _2=71, _3=71, _4=74)
Pandas(Index=88, gender='female', _2=58, _3=70, _4=67)
Pandas(Index=89, gender='female', _2=73, _3=86, _4=82)
Pandas(Index=90, gender='female', _2=65, _3=72, _4=74)
Pandas(Index=91, gender='male', _2=27, _3=34, _4=36)
Pandas(Index=92, gender='male', _2=71, _3=79, _4=71)
Pandas(Index=93, gender='male', _2=43, _3=45, _4=50)
Pandas(Index=94, gender='female', _2=79, _3=86, _4=92)
Pandas(Index=95, gender='male', _2=78, _3=81, _4=82)
Pandas(Index=96, gender='male', _2=65, _3=66, _4=62)
Pandas(Index=97, gender='female', _2=63, _3=72, _4=70)
Pandas(Index=98, gender='female', _2=58, _3=67, _4=62)
Pandas(Index=99, gender='female', _2=65, _3=67, _4=62)
Pandas(Index=100, gender='male', _2=79, _3=67, _4=67)
Pandas(Index=101, gender='male', _2=68, _3=74, _4=74)
Pandas(Index=102, gender='female', _2=85, _3=91, _4=89)
Pandas(Index=103, gender='male', _2=60, _3=44, _4=47)
Pandas(Index=104, gender='male', _2=98, _3=86, _4=90)
Pandas(Index=105, gender='female', _2=58, _3=67, _4=72)
Pandas(Index=106, gender='female', _2=87, _3=100, _4=100)
Pandas(Index=107, gender='male', _2=66, _3=63, _4=64)
Pandas(Index=108, gender='female', _2=52, _3=76, _4=70)
Pandas(Index=109, gender='female', _2=70, _3=64, _4=72)
Pandas(Index=110, gender='female', _2=77, _3=89, _4=98)
Pandas(Index=111, gender='male', _2=62, _3=55, _4=49)
Pandas(Index=112, gender='male', _2=54, _3=53, _4=47)
Pandas(Index=113, gender='female', _2=51, _3=58, _4=54)
Pandas(Index=114, gender='female', _2=99, _3=100, _4=100)
Pandas(Index=115, gender='male', _2=84, _3=77, _4=74)
Pandas(Index=116, gender='female', _2=75, _3=85, _4=82)
Pandas(Index=117, gender='female', _2=78, _3=82, _4=79)
Pandas(Index=118, gender='female', _2=51, _3=63, _4=61)
Pandas(Index=119, gender='female', _2=55, _3=69, _4=65)
Pandas(Index=120, gender='female', _2=79, _3=92, _4=89)
Pandas(Index=121, gender='male', _2=91, _3=89, _4=92)
Pandas(Index=122, gender='female', _2=88, _3=93, _4=93)
Pandas(Index=123, gender='male', _2=63, _3=57, _4=56)
Pandas(Index=124, gender='male', _2=83, _3=80, _4=73)
Pandas(Index=125, gender='female', _2=87, _3=95, _4=86)
Pandas(Index=126, gender='male', _2=72, _3=68, _4=67)
Pandas(Index=127, gender='male', _2=65, _3=77, _4=74)
Pandas(Index=128, gender='male', _2=82, _3=82, _4=74)
Pandas(Index=129, gender='female', _2=51, _3=49, _4=51)
Pandas(Index=130, gender='male', _2=89, _3=84, _4=82)
Pandas(Index=131, gender='male', _2=53, _3=37, _4=40)
Pandas(Index=132, gender='male', _2=87, _3=74, _4=70)
Pandas(Index=133, gender='female', _2=75, _3=81, _4=84)
Pandas(Index=134, gender='male', _2=74, _3=79, _4=75)
Pandas(Index=135, gender='male', _2=58, _3=55, _4=48)
Pandas(Index=136, gender='male', _2=51, _3=54, _4=41)
Pandas(Index=137, gender='male', _2=70, _3=55, _4=56)
Pandas(Index=138, gender='female', _2=59, _3=66, _4=67)
Pandas(Index=139, gender='male', _2=71, _3=61, _4=69)
Pandas(Index=140, gender='female', _2=76, _3=72, _4=71)
Pandas(Index=141, gender='female', _2=59, _3=62, _4=64)
Pandas(Index=142, gender='female', _2=42, _3=55, _4=54)
Pandas(Index=143, gender='male', _2=57, _3=43, _4=47)
Pandas(Index=144, gender='male', _2=88, _3=73, _4=78)
Pandas(Index=145, gender='female', _2=22, _3=39, _4=33)
Pandas(Index=146, gender='male', _2=88, _3=84, _4=75)
Pandas(Index=147, gender='male', _2=73, _3=68, _4=66)
Pandas(Index=148, gender='female', _2=68, _3=75, _4=81)
Pandas(Index=149, gender='male', _2=100, _3=100, _4=93)
Pandas(Index=150, gender='male', _2=62, _3=67, _4=69)
Pandas(Index=151, gender='male', _2=77, _3=67, _4=68)
Pandas(Index=152, gender='female', _2=59, _3=70, _4=66)
Pandas(Index=153, gender='male', _2=54, _3=49, _4=47)
Pandas(Index=154, gender='male', _2=62, _3=67, _4=61)
Pandas(Index=155, gender='female', _2=70, _3=89, _4=88)
Pandas(Index=156, gender='female', _2=66, _3=74, _4=78)
Pandas(Index=157, gender='male', _2=60, _3=60, _4=60)
Pandas(Index=158, gender='female', _2=61, _3=86, _4=87)
Pandas(Index=159, gender='male', _2=66, _3=62, _4=64)
Pandas(Index=160, gender='male', _2=82, _3=78, _4=74)
Pandas(Index=161, gender='female', _2=75, _3=88, _4=85)
Pandas(Index=162, gender='male', _2=49, _3=53, _4=52)
Pandas(Index=163, gender='male', _2=52, _3=53, _4=49)
Pandas(Index=164, gender='female', _2=81, _3=92, _4=91)
Pandas(Index=165, gender='female', _2=96, _3=100, _4=100)
Pandas(Index=166, gender='male', _2=53, _3=51, _4=51)
Pandas(Index=167, gender='female', _2=58, _3=76, _4=78)
Pandas(Index=168, gender='female', _2=68, _3=83, _4=78)
Pandas(Index=169, gender='female', _2=67, _3=75, _4=70)
Pandas(Index=170, gender='male', _2=72, _3=73, _4=74)
Pandas(Index=171, gender='male', _2=94, _3=88, _4=78)
Pandas(Index=172, gender='female', _2=79, _3=86, _4=81)
Pandas(Index=173, gender='female', _2=63, _3=67, _4=70)
Pandas(Index=174, gender='female', _2=43, _3=51, _4=54)
Pandas(Index=175, gender='female', _2=81, _3=91, _4=87)
Pandas(Index=176, gender='female', _2=46, _3=54, _4=58)
Pandas(Index=177, gender='female', _2=71, _3=77, _4=77)
Pandas(Index=178, gender='female', _2=52, _3=70, _4=62)
Pandas(Index=179, gender='female', _2=97, _3=100, _4=100)
Pandas(Index=180, gender='male', _2=62, _3=68, _4=75)
Pandas(Index=181, gender='female', _2=46, _3=64, _4=66)
Pandas(Index=182, gender='female', _2=50, _3=50, _4=47)
Pandas(Index=183, gender='female', _2=65, _3=69, _4=70)
Pandas(Index=184, gender='male', _2=45, _3=52, _4=49)
Pandas(Index=185, gender='male', _2=65, _3=67, _4=65)
Pandas(Index=186, gender='male', _2=80, _3=76, _4=65)
Pandas(Index=187, gender='male', _2=62, _3=66, _4=68)
Pandas(Index=188, gender='male', _2=48, _3=52, _4=45)
Pandas(Index=189, gender='female', _2=77, _3=88, _4=87)
Pandas(Index=190, gender='female', _2=66, _3=65, _4=69)
Pandas(Index=191, gender='male', _2=76, _3=83, _4=79)
Pandas(Index=192, gender='female', _2=62, _3=64, _4=66)
Pandas(Index=193, gender='male', _2=77, _3=62, _4=62)
Pandas(Index=194, gender='female', _2=69, _3=84, _4=85)
Pandas(Index=195, gender='male', _2=61, _3=55, _4=52)
Pandas(Index=196, gender='male', _2=59, _3=69, _4=65)
Pandas(Index=197, gender='male', _2=55, _3=56, _4=51)
Pandas(Index=198, gender='female', _2=45, _3=53, _4=55)
Pandas(Index=199, gender='female', _2=78, _3=79, _4=76)
Pandas(Index=200, gender='female', _2=67, _3=84, _4=86)
Pandas(Index=201, gender='female', _2=65, _3=81, _4=77)
Pandas(Index=202, gender='male', _2=69, _3=77, _4=69)
Pandas(Index=203, gender='female', _2=57, _3=69, _4=68)
Pandas(Index=204, gender='male', _2=59, _3=41, _4=42)
Pandas(Index=205, gender='male', _2=74, _3=71, _4=78)
Pandas(Index=206, gender='male', _2=82, _3=62, _4=62)
Pandas(Index=207, gender='male', _2=81, _3=80, _4=76)
Pandas(Index=208, gender='female', _2=74, _3=81, _4=76)
Pandas(Index=209, gender='female', _2=58, _3=61, _4=66)
Pandas(Index=210, gender='male', _2=80, _3=79, _4=79)
Pandas(Index=211, gender='male', _2=35, _3=28, _4=27)
Pandas(Index=212, gender='female', _2=42, _3=62, _4=60)
Pandas(Index=213, gender='male', _2=60, _3=51, _4=56)
Pandas(Index=214, gender='male', _2=87, _3=91, _4=81)
Pandas(Index=215, gender='male', _2=84, _3=83, _4=75)
Pandas(Index=216, gender='female', _2=83, _3=86, _4=88)
Pandas(Index=217, gender='female', _2=34, _3=42, _4=39)
Pandas(Index=218, gender='male', _2=66, _3=77, _4=70)
Pandas(Index=219, gender='male', _2=61, _3=56, _4=56)
Pandas(Index=220, gender='female', _2=56, _3=68, _4=74)
Pandas(Index=221, gender='male', _2=87, _3=85, _4=73)
Pandas(Index=222, gender='female', _2=55, _3=65, _4=62)
Pandas(Index=223, gender='male', _2=86, _3=80, _4=75)
Pandas(Index=224, gender='female', _2=52, _3=66, _4=73)
Pandas(Index=225, gender='female', _2=45, _3=56, _4=54)
Pandas(Index=226, gender='female', _2=72, _3=72, _4=71)
Pandas(Index=227, gender='male', _2=57, _3=50, _4=54)
Pandas(Index=228, gender='male', _2=68, _3=72, _4=64)
Pandas(Index=229, gender='female', _2=88, _3=95, _4=94)
Pandas(Index=230, gender='male', _2=76, _3=64, _4=66)
Pandas(Index=231, gender='male', _2=46, _3=43, _4=42)
Pandas(Index=232, gender='female', _2=67, _3=86, _4=83)
Pandas(Index=233, gender='male', _2=92, _3=87, _4=78)
Pandas(Index=234, gender='male', _2=83, _3=82, _4=84)
Pandas(Index=235, gender='male', _2=80, _3=75, _4=77)
Pandas(Index=236, gender='male', _2=63, _3=66, _4=67)
Pandas(Index=237, gender='female', _2=64, _3=60, _4=74)
Pandas(Index=238, gender='male', _2=54, _3=52, _4=51)
Pandas(Index=239, gender='male', _2=84, _3=80, _4=80)
Pandas(Index=240, gender='male', _2=73, _3=68, _4=66)
Pandas(Index=241, gender='female', _2=80, _3=83, _4=83)
Pandas(Index=242, gender='female', _2=56, _3=52, _4=55)
Pandas(Index=243, gender='male', _2=59, _3=51, _4=43)
Pandas(Index=244, gender='male', _2=75, _3=74, _4=69)
Pandas(Index=245, gender='male', _2=85, _3=76, _4=71)
Pandas(Index=246, gender='male', _2=89, _3=76, _4=74)
Pandas(Index=247, gender='female', _2=58, _3=70, _4=68)
Pandas(Index=248, gender='female', _2=65, _3=64, _4=62)
Pandas(Index=249, gender='male', _2=68, _3=60, _4=53)
Pandas(Index=250, gender='male', _2=47, _3=49, _4=49)
Pandas(Index=251, gender='female', _2=71, _3=83, _4=83)
Pandas(Index=252, gender='female', _2=60, _3=70, _4=70)
Pandas(Index=253, gender='male', _2=80, _3=80, _4=72)
Pandas(Index=254, gender='male', _2=54, _3=52, _4=52)
Pandas(Index=255, gender='female', _2=62, _3=73, _4=70)
Pandas(Index=256, gender='female', _2=64, _3=73, _4=68)
Pandas(Index=257, gender='male', _2=78, _3=77, _4=77)
Pandas(Index=258, gender='female', _2=70, _3=75, _4=78)
Pandas(Index=259, gender='female', _2=65, _3=81, _4=81)
Pandas(Index=260, gender='female', _2=64, _3=79, _4=77)
Pandas(Index=261, gender='male', _2=79, _3=79, _4=78)
Pandas(Index=262, gender='female', _2=44, _3=50, _4=51)
Pandas(Index=263, gender='female', _2=99, _3=93, _4=90)
Pandas(Index=264, gender='male', _2=76, _3=73, _4=68)
Pandas(Index=265, gender='male', _2=59, _3=42, _4=41)
Pandas(Index=266, gender='female', _2=63, _3=75, _4=81)
Pandas(Index=267, gender='female', _2=69, _3=72, _4=77)
Pandas(Index=268, gender='female', _2=88, _3=92, _4=95)
Pandas(Index=269, gender='female', _2=71, _3=76, _4=70)
Pandas(Index=270, gender='male', _2=69, _3=63, _4=61)
Pandas(Index=271, gender='male', _2=58, _3=49, _4=42)
Pandas(Index=272, gender='female', _2=47, _3=53, _4=58)
Pandas(Index=273, gender='female', _2=65, _3=70, _4=71)
Pandas(Index=274, gender='male', _2=88, _3=85, _4=76)
Pandas(Index=275, gender='male', _2=83, _3=78, _4=73)
Pandas(Index=276, gender='female', _2=85, _3=92, _4=93)
Pandas(Index=277, gender='female', _2=59, _3=63, _4=75)
Pandas(Index=278, gender='female', _2=65, _3=86, _4=80)
Pandas(Index=279, gender='male', _2=73, _3=56, _4=57)
Pandas(Index=280, gender='male', _2=53, _3=52, _4=42)
Pandas(Index=281, gender='male', _2=45, _3=48, _4=46)
Pandas(Index=282, gender='female', _2=73, _3=79, _4=84)
Pandas(Index=283, gender='female', _2=70, _3=78, _4=78)
Pandas(Index=284, gender='female', _2=37, _3=46, _4=46)
Pandas(Index=285, gender='male', _2=81, _3=82, _4=82)
Pandas(Index=286, gender='male', _2=97, _3=82, _4=88)
Pandas(Index=287, gender='female', _2=67, _3=89, _4=82)
Pandas(Index=288, gender='male', _2=88, _3=75, _4=76)
Pandas(Index=289, gender='male', _2=77, _3=76, _4=77)
Pandas(Index=290, gender='male', _2=76, _3=70, _4=68)
Pandas(Index=291, gender='male', _2=86, _3=73, _4=70)
Pandas(Index=292, gender='male', _2=63, _3=60, _4=57)
Pandas(Index=293, gender='female', _2=65, _3=73, _4=75)
Pandas(Index=294, gender='male', _2=78, _3=77, _4=80)
Pandas(Index=295, gender='male', _2=67, _3=62, _4=60)
Pandas(Index=296, gender='male', _2=46, _3=41, _4=43)
Pandas(Index=297, gender='male', _2=71, _3=74, _4=68)
Pandas(Index=298, gender='male', _2=40, _3=46, _4=50)
Pandas(Index=299, gender='male', _2=90, _3=87, _4=75)
Pandas(Index=300, gender='male', _2=81, _3=78, _4=81)
Pandas(Index=301, gender='male', _2=56, _3=54, _4=52)
Pandas(Index=302, gender='female', _2=67, _3=84, _4=81)
Pandas(Index=303, gender='male', _2=80, _3=76, _4=64)
Pandas(Index=304, gender='female', _2=74, _3=75, _4=83)
Pandas(Index=305, gender='male', _2=69, _3=67, _4=69)
Pandas(Index=306, gender='male', _2=99, _3=87, _4=81)
Pandas(Index=307, gender='male', _2=51, _3=52, _4=44)
Pandas(Index=308, gender='female', _2=53, _3=71, _4=67)
Pandas(Index=309, gender='female', _2=49, _3=57, _4=52)
Pandas(Index=310, gender='female', _2=73, _3=76, _4=80)
Pandas(Index=311, gender='male', _2=66, _3=60, _4=57)
Pandas(Index=312, gender='male', _2=67, _3=61, _4=68)
Pandas(Index=313, gender='female', _2=68, _3=67, _4=69)
Pandas(Index=314, gender='female', _2=59, _3=64, _4=75)
Pandas(Index=315, gender='male', _2=71, _3=66, _4=65)
Pandas(Index=316, gender='female', _2=77, _3=82, _4=91)
Pandas(Index=317, gender='male', _2=83, _3=72, _4=78)
Pandas(Index=318, gender='male', _2=63, _3=71, _4=69)
Pandas(Index=319, gender='female', _2=56, _3=65, _4=63)
Pandas(Index=320, gender='female', _2=67, _3=79, _4=84)
Pandas(Index=321, gender='female', _2=75, _3=86, _4=79)
Pandas(Index=322, gender='female', _2=71, _3=81, _4=80)
Pandas(Index=323, gender='female', _2=43, _3=53, _4=53)
Pandas(Index=324, gender='female', _2=41, _3=46, _4=43)
Pandas(Index=325, gender='female', _2=82, _3=90, _4=94)
Pandas(Index=326, gender='male', _2=61, _3=61, _4=62)
Pandas(Index=327, gender='male', _2=28, _3=23, _4=19)
Pandas(Index=328, gender='male', _2=82, _3=75, _4=77)
Pandas(Index=329, gender='female', _2=41, _3=55, _4=51)
Pandas(Index=330, gender='male', _2=71, _3=60, _4=61)
Pandas(Index=331, gender='male', _2=47, _3=37, _4=35)
Pandas(Index=332, gender='male', _2=62, _3=56, _4=53)
Pandas(Index=333, gender='male', _2=90, _3=78, _4=81)
Pandas(Index=334, gender='female', _2=83, _3=93, _4=95)
Pandas(Index=335, gender='female', _2=61, _3=68, _4=66)
Pandas(Index=336, gender='male', _2=76, _3=70, _4=69)
Pandas(Index=337, gender='male', _2=49, _3=51, _4=43)
Pandas(Index=338, gender='female', _2=24, _3=38, _4=27)
Pandas(Index=339, gender='female', _2=35, _3=55, _4=60)
Pandas(Index=340, gender='male', _2=58, _3=61, _4=52)
Pandas(Index=341, gender='female', _2=61, _3=73, _4=63)
Pandas(Index=342, gender='female', _2=69, _3=76, _4=74)
Pandas(Index=343, gender='male', _2=67, _3=72, _4=67)
Pandas(Index=344, gender='male', _2=79, _3=73, _4=67)
Pandas(Index=345, gender='female', _2=72, _3=80, _4=75)
Pandas(Index=346, gender='male', _2=62, _3=61, _4=57)
Pandas(Index=347, gender='female', _2=77, _3=94, _4=95)
Pandas(Index=348, gender='male', _2=75, _3=74, _4=66)
Pandas(Index=349, gender='male', _2=87, _3=74, _4=76)
Pandas(Index=350, gender='female', _2=52, _3=65, _4=69)
Pandas(Index=351, gender='male', _2=66, _3=57, _4=52)
Pandas(Index=352, gender='female', _2=63, _3=78, _4=80)
Pandas(Index=353, gender='female', _2=46, _3=58, _4=57)
Pandas(Index=354, gender='female', _2=59, _3=71, _4=70)
Pandas(Index=355, gender='female', _2=61, _3=72, _4=70)
Pandas(Index=356, gender='male', _2=63, _3=61, _4=61)
Pandas(Index=357, gender='female', _2=42, _3=66, _4=69)
Pandas(Index=358, gender='male', _2=59, _3=62, _4=61)
Pandas(Index=359, gender='female', _2=80, _3=90, _4=89)
Pandas(Index=360, gender='female', _2=58, _3=62, _4=59)
Pandas(Index=361, gender='male', _2=85, _3=84, _4=78)
Pandas(Index=362, gender='female', _2=52, _3=58, _4=58)
Pandas(Index=363, gender='female', _2=27, _3=34, _4=32)
Pandas(Index=364, gender='male', _2=59, _3=60, _4=58)

In [7]:
for row in df.itertuples():
    print(row.gender)

female
female
female
male
male
female
female
male
male
female
male
male
female
male
female
female
male
female
male
female
male
female
male
female
male
male
male
female
male
female
female
female
female
male
male
male
female
female
female
male
male
female
female
male
female
male
female
female
female
male
male
male
male
male
female
female
female
male
male
female
male
male
male
female
female
male
male
female
male
female
female
male
female
male
male
male
male
male
female
female
female
male
male
male
male
female
female
female
female
female
female
male
male
male
female
male
male
female
female
female
male
male
female
male
male
female
female
male
female
female
female
male
male
female
female
male
female
female
female
female
female
male
female
male
male
female
male
male
male
female
male
male
male
female
male
male
male
male
female
male
female
female
female
male
male
female
male
male
female
male
male
male
female
male
male
female
female
male
female
male
male
female
male
male
female
female
male
female
female
female
male
male
female
female
female
female
female
female
female
female
male
female
female
female
male
male
male
male
male
female
female
male
female
male
female
male
male
male
female
female
female
female
male
female
male
male
male
male
female
female
male
male
female
male
male
male
female
female
male
male
female
male
female
male
female
female
female
male
male
female
male
male
female
male
male
male
male
female
male
male
male
female
female
male
male
male
male
female
female
male
male
female
female
male
male
female
female
male
female
female
female
male
female
female
male
male
female
female
female
female
male
male
female
female
male
male
female
female
female
male
male
male
female
female
female
male
male
female
male
male
male
male
male
female
male
male
male
male
male
male
male
male
female
male
female
male
male
male
female
female
female
male
male
female
female
male
female
male
male
female
female
female
female
female
female
female
male
male
male
female
male
male
male
male
female
female
male
male
female
female
male
female
female
male
male
female
male
female
male
male
female
male
female
female
female
female
male
female
male
female
female
male
female
female
male
male
male
male
female
female
male
female
male
female
female
male
female
female
female
male
female
male
male
female
female
female
female
female
female
male
male
female
male
male
female
male
female
female
male
male
female
male
female
female
female
female
male
female
female
male
female
male
male
male
female
male
male
male
male
male
female
female
female
female
male
female
male
male
male
male
male
female
male
female
male
male
male
male
male
male
female
female
female
female
male
female
male
male
male
male
female
female
female
male
female
male
female
male
female
male
male
male
female
female
male
female
female
male
female
male
female
female
female
female
female
female
male
male
female
male
male
female
male
male
female
male
male
female
male
male
female
female
female
female
female
male
female
female
female
male
female
female
male
female
female
female
male
male
male
female
male
male
male
female
female
female
female
female
female
female
male
female
male
male
male
male
male
female
female
female
female
female
male
female
male
female
male
female
male
male
male
male
female
female
female
male
female
male
female
male
male
male
female
male
male
female
female
male
female
male
female
female
male
female
male
male
female
female
male
male
male
male
female
female
female
male
male
female
female
female
female
female
female
female
female
female
female
female
female
female
male
male
male
female
female
female
male
male
female
female
female
female
female
male
male
male
female
female
female
female
male
female
male
female
female
female
female
male
male
male
female
male
male
male
female
male
male
male
male
female
male
male
female
female
male
male
female
female
male
female
male
female
female
female
male
female
female
female
female
female
male
female
female
female
female
female
male
male
female
male
male
male
female
female
male
female
female
female
male
male
female
male
female
female
female
female
female
female
male
male
female
male
male
female
male
female
male
male
male
male
female
female
female
female
female
female
female
female
female
male
female
female
male
female
female
male
male
male
male
female
male
female
female
male
female
female
male
female
female
male
female
male
female
male
male
male
female
male
female
male
female
male
female
male
female
male
male
female
male
male
male
female
female
female
male
male
male
male
female
male
male
male
male
female
male
female
male
male
female
male
female
female
male
female
male
female
female
male
female
male
male
male
female
female
male
female
female
female
female
male
female
female
female
female
male
female
female
female
male
female
female
female
male
male
female
female
male
female
male
female
male
male
female
female
female
male
female
female
male
male
male
male
female
male
female
male
female
male
female
female
female
female
male
female
female
male
female
female
female
male
female
female
male
female
male
female
male
female
male
female
female
male
female
male
female
male
male
male
female
male
male
female
female
male
male
female
male
female
male
male
female
female
male
female
male
male
male
male
male
male
male
female
male
male
female
male
male
male
female
female
male
female
female
male
female
female
female
male
female
male
female
female
female
male
female
female
male
female
male
female
male
female
female
female
female
male
male
female
female
male
male
female
female
female
female
female
male
female
female
male
male
female
male
female
male
male
male
female
male
female
male
male
male
male
male
male
male
female
male
male
male
female
male
male
female
female
male
female
male
female
male
female
female
male
female
male
male
female
female
male
female
female
female
female
male
female
male
male
female
female
female
male
female
female
female
female
male
male
male
female
female
male
male
female
female
male
female
male
female
female
male
female
female
female
male
female
male
female
female
female

In [8]:
for col in df.columns:
    print(df[col][2])

female
90
95
93

In [9]:
for label, col in df.items():
    print(label, col.values)

gender ['female' 'female' 'female' 'male' 'male' 'female' 'female' 'male' 'male'
 'female' 'male' 'male' 'female' 'male' 'female' 'female' 'male' 'female'
 'male' 'female' 'male' 'female' 'male' 'female' 'male' 'male' 'male'
 'female' 'male' 'female' 'female' 'female' 'female' 'male' 'male' 'male'
 'female' 'female' 'female' 'male' 'male' 'female' 'female' 'male'
 'female' 'male' 'female' 'female' 'female' 'male' 'male' 'male' 'male'
 'male' 'female' 'female' 'female' 'male' 'male' 'female' 'male' 'male'
 'male' 'female' 'female' 'male' 'male' 'female' 'male' 'female' 'female'
 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'female' 'female'
 'female' 'male' 'male' 'male' 'male' 'female' 'female' 'female' 'female'
 'female' 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'female'
 'female' 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'female'
 'male' 'female' 'female' 'female' 'male' 'male' 'female' 'female' 'male'
 'female' 'female' 'female' 'female' 'female' 'male' 'female' 'male'
 'male' 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'male'
 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'female' 'female'
 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'male'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'male'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'female'
 'female' 'male' 'male' 'female' 'female' 'female' 'female' 'female'
 'female' 'female' 'female' 'male' 'female' 'female' 'female' 'male'
 'male' 'male' 'male' 'male' 'female' 'female' 'male' 'female' 'male'
 'female' 'male' 'male' 'male' 'female' 'female' 'female' 'female' 'male'
 'female' 'male' 'male' 'male' 'male' 'female' 'female' 'male' 'male'
 'female' 'male' 'male' 'male' 'female' 'female' 'male' 'male' 'female'
 'male' 'female' 'male' 'female' 'female' 'female' 'male' 'male' 'female'
 'male' 'male' 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'male'
 'male' 'female' 'female' 'male' 'male' 'male' 'male' 'female' 'female'
 'male' 'male' 'female' 'female' 'male' 'male' 'female' 'female' 'male'
 'female' 'female' 'female' 'male' 'female' 'female' 'male' 'male'
 'female' 'female' 'female' 'female' 'male' 'male' 'female' 'female'
 'male' 'male' 'female' 'female' 'female' 'male' 'male' 'male' 'female'
 'female' 'female' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'male'
 'female' 'male' 'female' 'male' 'male' 'male' 'female' 'female' 'female'
 'male' 'male' 'female' 'female' 'male' 'female' 'male' 'male' 'female'
 'female' 'female' 'female' 'female' 'female' 'female' 'male' 'male'
 'male' 'female' 'male' 'male' 'male' 'male' 'female' 'female' 'male'
 'male' 'female' 'female' 'male' 'female' 'female' 'male' 'male' 'female'
 'male' 'female' 'male' 'male' 'female' 'male' 'female' 'female' 'female'
 'female' 'male' 'female' 'male' 'female' 'female' 'male' 'female'
 'female' 'male' 'male' 'male' 'male' 'female' 'female' 'male' 'female'
 'male' 'female' 'female' 'male' 'female' 'female' 'female' 'male'
 'female' 'male' 'male' 'female' 'female' 'female' 'female' 'female'
 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'female'
 'female' 'male' 'male' 'female' 'male' 'female' 'female' 'female'
 'female' 'male' 'female' 'female' 'male' 'female' 'male' 'male' 'male'
 'female' 'male' 'male' 'male' 'male' 'male' 'female' 'female' 'female'
 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'female'
 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'female'
 'female' 'female' 'female' 'male' 'female' 'male' 'male' 'male' 'male'
 'female' 'female' 'female' 'male' 'female' 'male' 'female' 'male'
 'female' 'male' 'male' 'male' 'female' 'female' 'male' 'female' 'female'
 'male' 'female' 'male' 'female' 'female' 'female' 'female' 'female'
 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'male'
 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'female' 'female'
 'female' 'female' 'male' 'female' 'female' 'female' 'male' 'female'
 'female' 'male' 'female' 'female' 'female' 'male' 'male' 'male' 'female'
 'male' 'male' 'male' 'female' 'female' 'female' 'female' 'female'
 'female' 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'male'
 'female' 'female' 'female' 'female' 'female' 'male' 'female' 'male'
 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'female' 'female'
 'female' 'male' 'female' 'male' 'female' 'male' 'male' 'male' 'female'
 'male' 'male' 'female' 'female' 'male' 'female' 'male' 'female' 'female'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'male' 'male'
 'male' 'female' 'female' 'female' 'male' 'male' 'female' 'female'
 'female' 'female' 'female' 'female' 'female' 'female' 'female' 'female'
 'female' 'female' 'female' 'male' 'male' 'male' 'female' 'female'
 'female' 'male' 'male' 'female' 'female' 'female' 'female' 'female'
 'male' 'male' 'male' 'female' 'female' 'female' 'female' 'male' 'female'
 'male' 'female' 'female' 'female' 'female' 'male' 'male' 'male' 'female'
 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male' 'female' 'male'
 'male' 'female' 'female' 'male' 'male' 'female' 'female' 'male' 'female'
 'male' 'female' 'female' 'female' 'male' 'female' 'female' 'female'
 'female' 'female' 'male' 'female' 'female' 'female' 'female' 'female'
 'male' 'male' 'female' 'male' 'male' 'male' 'female' 'female' 'male'
 'female' 'female' 'female' 'male' 'male' 'female' 'male' 'female'
 'female' 'female' 'female' 'female' 'female' 'male' 'male' 'female'
 'male' 'male' 'female' 'male' 'female' 'male' 'male' 'male' 'male'
 'female' 'female' 'female' 'female' 'female' 'female' 'female' 'female'
 'female' 'male' 'female' 'female' 'male' 'female' 'female' 'male' 'male'
 'male' 'male' 'female' 'male' 'female' 'female' 'male' 'female' 'female'
 'male' 'female' 'female' 'male' 'female' 'male' 'female' 'male' 'male'
 'male' 'female' 'male' 'female' 'male' 'female' 'male' 'female' 'male'
 'female' 'male' 'male' 'female' 'male' 'male' 'male' 'female' 'female'
 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'female' 'male' 'female' 'male' 'male' 'female' 'male' 'female' 'female'
 'male' 'female' 'male' 'female' 'female' 'male' 'female' 'male' 'male'
 'male' 'female' 'female' 'male' 'female' 'female' 'female' 'female'
 'male' 'female' 'female' 'female' 'female' 'male' 'female' 'female'
 'female' 'male' 'female' 'female' 'female' 'male' 'male' 'female'
 'female' 'male' 'female' 'male' 'female' 'male' 'male' 'female' 'female'
 'female' 'male' 'female' 'female' 'male' 'male' 'male' 'male' 'female'
 'male' 'female' 'male' 'female' 'male' 'female' 'female' 'female'
 'female' 'male' 'female' 'female' 'male' 'female' 'female' 'female'
 'male' 'female' 'female' 'male' 'female' 'male' 'female' 'male' 'female'
 'male' 'female' 'female' 'male' 'female' 'male' 'female' 'male' 'male'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'male' 'female'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'male'
 'male' 'male' 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'female'
 'male' 'male' 'male' 'female' 'female' 'male' 'female' 'female' 'male'
 'female' 'female' 'female' 'male' 'female' 'male' 'female' 'female'
 'female' 'male' 'female' 'female' 'male' 'female' 'male' 'female' 'male'
 'female' 'female' 'female' 'female' 'male' 'male' 'female' 'female'
 'male' 'male' 'female' 'female' 'female' 'female' 'female' 'male'
 'female' 'female' 'male' 'male' 'female' 'male' 'female' 'male' 'male'
 'male' 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'male'
 'male' 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'female'
 'female' 'male' 'female' 'male' 'female' 'male' 'female' 'female' 'male'
 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'female'
 'female' 'female' 'male' 'female' 'male' 'male' 'female' 'female'
 'female' 'male' 'female' 'female' 'female' 'female' 'male' 'male' 'male'
 'female' 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'male'
 'female' 'female' 'male' 'female' 'female' 'female' 'male' 'female'
 'male' 'female' 'female' 'female']
math score [ 72  69  90  47  76  71  88  40  64  38  58  40  65  78  50  69  88  18
  46  54  66  65  44  69  74  73  69  67  70  62  69  63  56  40  97  81
  74  50  75  57  55  58  53  59  50  65  55  66  57  82  53  77  53  88
  71  33  82  52  58   0  79  39  62  69  59  67  45  60  61  39  58  63
  41  61  49  44  30  80  61  62  47  49  50  72  42  73  76  71  58  73
  65  27  71  43  79  78  65  63  58  65  79  68  85  60  98  58  87  66
  52  70  77  62  54  51  99  84  75  78  51  55  79  91  88  63  83  87
  72  65  82  51  89  53  87  75  74  58  51  70  59  71  76  59  42  57
  88  22  88  73  68 100  62  77  59  54  62  70  66  60  61  66  82  75
  49  52  81  96  53  58  68  67  72  94  79  63  43  81  46  71  52  97
  62  46  50  65  45  65  80  62  48  77  66  76  62  77  69  61  59  55
  45  78  67  65  69  57  59  74  82  81  74  58  80  35  42  60  87  84
  83  34  66  61  56  87  55  86  52  45  72  57  68  88  76  46  67  92
  83  80  63  64  54  84  73  80  56  59  75  85  89  58  65  68  47  71
  60  80  54  62  64  78  70  65  64  79  44  99  76  59  63  69  88  71
  69  58  47  65  88  83  85  59  65  73  53  45  73  70  37  81  97  67
  88  77  76  86  63  65  78  67  46  71  40  90  81  56  67  80  74  69
  99  51  53  49  73  66  67  68  59  71  77  83  63  56  67  75  71  43
  41  82  61  28  82  41  71  47  62  90  83  61  76  49  24  35  58  61
  69  67  79  72  62  77  75  87  52  66  63  46  59  61  63  42  59  80
  58  85  52  27  59  49  69  61  44  73  84  45  74  82  59  46  80  85
  71  66  80  87  79  38  38  67  64  57  62  73  73  77  76  57  65  48
  50  85  74  60  59  53  49  88  54  63  65  82  52  87  70  84  71  63
  51  84  71  74  68  57  82  57  47  59  41  62  86  69  65  68  64  61
  61  47  73  50  75  75  70  89  67  78  59  73  79  67  69  86  47  81
  64 100  65  65  53  37  79  53 100  72  53  54  71  77  75  84  26  72
  77  91  83  63  68  59  90  71  76  80  55  76  73  52  68  59  49  70
  61  60  64  79  65  64  83  81  54  68  54  59  66  76  74  94  63  95
  40  82  68  55  79  86  76  64  62  54  77  76  74  66  66  67  71  91
  69  54  53  68  56  36  29  62  68  47  62  79  73  66  51  51  85  97
  75  79  81  82  64  78  92  72  62  79  79  87  40  77  53  32  55  61
  53  73  74  63  96  63  48  48  92  61  63  68  71  91  53  50  74  40
  61  81  48  53  81  77  63  73  69  65  55  44  54  48  58  71  68  74
  92  56  30  53  69  65  54  29  76  60  84  75  85  40  61  58  69  58
  94  65  82  60  37  88  95  65  35  62  58 100  61 100  69  61  49  44
  67  79  66  75  84  71  67  80  86  76  41  74  72  74  70  65  59  64
  50  69  51  68  85  65  73  62  77  69  43  90  74  73  55  65  80  50
  63  77  73  81  66  52  69  65  69  50  73  70  81  63  67  60  62  29
  62  94  85  77  53  93  49  73  66  77  49  79  75  59  57  66  79  57
  87  63  59  62  46  66  89  42  93  80  98  81  60  76  73  96  76  91
  62  55  74  50  47  81  65  68  73  53  68  55  87  55  53  67  92  53
  81  61  80  37  81  59  55  72  69  69  50  87  71  68  79  77  58  84
  55  70  52  69  53  48  78  62  60  74  58  76  68  58  52  75  52  62
  66  49  66  35  72  94  46  77  76  52  91  32  72  19  68  52  48  60
  66  89  42  57  70  70  69  52  67  76  87  82  73  75  64  41  90  59
  51  45  54  87  72  94  45  61  60  77  85  78  49  71  48  62  56  65
  69  68  61  74  64  77  58  60  73  75  58  66  39  64  23  74  40  90
  91  64  59  80  71  61  87  82  62  97  75  65  52  87  53  81  39  71
  97  82  59  61  78  49  59  70  82  90  43  80  81  57  59  64  63  71
  64  55  51  62  93  54  69  44  86  85  50  88  59  32  36  63  67  65
  85  73  34  93  67  88  57  79  67  70  50  69  52  47  46  68 100  44
  57  91  69  35  72  54  74  74  64  65  46  48  67  62  61  70  98  70
  67  57  85  77  72  78  81  61  58  54  82  49  49  57  94  75  74  58
  62  72  84  92  45  75  56  48 100  65  72  62  66  63  68  75  89  78
  53  49  54  64  60  62  55  91   8  81  79  78  74  57  40  81  44  67
  86  65  55  62  63  88  62  59  68  77]
reading score [ 72  90  95  57  78  83  95  43  64  60  54  52  81  72  53  75  89  32
  42  58  69  75  54  73  71  74  54  69  70  70  74  65  72  42  87  81
  81  64  90  56  61  73  58  65  56  54  65  71  74  84  55  69  44  78
  84  41  85  55  59  17  74  39  61  80  58  64  37  72  58  64  63  55
  51  57  49  41  26  78  74  68  49  45  47  64  39  80  83  71  70  86
  72  34  79  45  86  81  66  72  67  67  67  74  91  44  86  67 100  63
  76  64  89  55  53  58 100  77  85  82  63  69  92  89  93  57  80  95
  68  77  82  49  84  37  74  81  79  55  54  55  66  61  72  62  55  43
  73  39  84  68  75 100  67  67  70  49  67  89  74  60  86  62  78  88
  53  53  92 100  51  76  83  75  73  88  86  67  51  91  54  77  70 100
  68  64  50  69  52  67  76  66  52  88  65  83  64  62  84  55  69  56
  53  79  84  81  77  69  41  71  62  80  81  61  79  28  62  51  91  83
  86  42  77  56  68  85  65  80  66  56  72  50  72  95  64  43  86  87
  82  75  66  60  52  80  68  83  52  51  74  76  76  70  64  60  49  83
  70  80  52  73  73  77  75  81  79  79  50  93  73  42  75  72  92  76
  63  49  53  70  85  78  92  63  86  56  52  48  79  78  46  82  82  89
  75  76  70  73  60  73  77  62  41  74  46  87  78  54  84  76  75  67
  87  52  71  57  76  60  61  67  64  66  82  72  71  65  79  86  81  53
  46  90  61  23  75  55  60  37  56  78  93  68  70  51  38  55  61  73
  76  72  73  80  61  94  74  74  65  57  78  58  71  72  61  66  62  90
  62  84  58  34  60  58  58  66  64  84  77  73  74  97  70  43  90  95
  83  64  86 100  81  49  43  76  73  78  64  70  67  68  67  54  74  45
  67  89  63  59  54  43  65  99  59  73  65  80  57  84  71  83  66  67
  72  73  74  73  59  56  93  58  58  85  39  67  83  71  59  63  66  72
  56  59  66  48  68  66  56  88  81  81  73  83  82  74  66  81  46  73
  85  92  77  58  61  56  89  54 100  65  58  54  70  90  58  87  31  67
  88  74  85  69  86  67  90  76  62  68  64  71  71  59  68  52  52  74
  47  75  53  82  85  64  83  88  64  64  48  78  69  71  79  87  61  89
  59  82  70  59  78  92  71  50  49  61  97  87  89  74  78  78  49  86
  58  59  52  60  61  53  41  74  67  54  61  88  69  83  60  66  66  92
  69  82  77  95  63  83 100  67  67  72  76  90  48  62  45  39  72  67
  70  66  75  74  90  80  51  43 100  71  48  68  75  96  62  66  81  55
  51  91  56  61  97  79  73  75  77  76  73  63  64  66  57  62  68  76
 100  79  24  54  77  82  60  29  78  57  89  72  84  58  64  63  60  59
  90  77  93  68  45  78  81  73  61  63  51  96  58  97  70  48  57  51
  64  60  74  88  84  74  80  92  76  74  52  88  81  79  65  81  70  62
  53  79  56  80  86  70  79  67  67  66  60  87  77  66  71  69  63  60
  73  85  74  72  76  57  78  84  77  64  78  82  75  61  72  68  55  40
  66  99  75  78  58  90  53  76  74  77  63  89  82  72  78  66  81  67
  84  64  63  72  34  59  87  61  84  85 100  81  70  94  78  96  76  73
  72  59  90  48  43  74  75  51  92  39  77  46  89  47  58  57  79  66
  71  60  73  57  84  73  55  79  75  64  60  84  69  72  77  90  55  95
  58  68  59  77  72  58  81  62  63  72  75  62  71  60  48  73  67  78
  65  58  72  44  79  85  56  90  85  59  81  51  79  38  65  65  62  66
  74  84  52  68  70  84  60  55  73  80  94  85  76  81  74  45  75  54
  31  47  64  84  80  86  59  70  72  91  90  90  52  87  58  67  68  69
  86  54  60  86  60  82  50  64  64  82  57  77  52  58  44  77  65  85
  85  54  72  75  67  68  85  67  64  97  68  79  49  73  62  86  42  71
  93  82  53  42  74  51  58  72  84  90  62  64  82  61  72  76  64  70
  73  46  51  76 100  72  65  51  85  92  67  74  62  34  29  78  54  78
  84  78  48 100  84  77  48  84  75  64  42  84  61  62  61  70 100  61
  77  96  70  53  66  65  70  64  56  61  43  56  74  57  71  75  87  63
  57  58  81  68  66  91  66  62  68  61  82  58  50  75  73  77  74  52
  69  57  87 100  63  81  58  54 100  76  57  70  68  63  76  84 100  72
  50  65  63  82  62  65  41  95  24  78  85  87  75  51  59  75  45  86
  81  82  76  72  63  99  55  71  78  86]
writing score [ 74  88  93  44  75  78  92  39  67  50  52  43  73  70  58  78  86  28
  46  61  63  70  53  73  80  72  55  75  65  75  74  61  65  38  82  79
  83  59  88  57  54  68  65  66  54  57  62  76  76  82  48  68  42  75
  87  43  86  49  58  10  72  34  55  71  59  61  37  74  56  57  73  63
  48  56  41  38  22  81  72  68  50  45  54  63  34  82  88  74  67  82
  74  36  71  50  92  82  62  70  62  62  67  74  89  47  90  72 100  64
  70  72  98  49  47  54 100  74  82  79  61  65  89  92  93  56  73  86
  67  74  74  51  82  40  70  84  75  48  41  56  67  69  71  64  54  47
  78  33  75  66  81  93  69  68  66  47  61  88  78  60  87  64  74  85
  52  49  91 100  51  78  78  70  74  78  81  70  54  87  58  77  62 100
  75  66  47  70  49  65  65  68  45  87  69  79  66  62  85  52  65  51
  55  76  86  77  69  68  42  78  62  76  76  66  79  27  60  56  81  75
  88  39  70  56  74  73  62  75  73  54  71  54  64  94  66  42  83  78
  84  77  67  74  51  80  66  83  55  43  69  71  74  68  62  53  49  83
  70  72  52  70  68  77  78  81  77  78  51  90  68  41  81  77  95  70
  61  42  58  71  76  73  93  75  80  57  42  46  84  78  46  82  88  82
  76  77  68  70  57  75  80  60  43  68  50  75  81  52  81  64  83  69
  81  44  67  52  80  57  68  69  75  65  91  78  69  63  84  79  80  53
  43  94  62  19  77  51  61  35  53  81  95  66  69  43  27  60  52  63
  74  67  67  75  57  95  66  76  69  52  80  57  70  70  61  69  61  89
  59  78  58  32  58  60  53  61  58  85  71  70  72  96  73  41  82 100
  77  62  83  95  71  45  43  75  70  67  64  75  59  77  67  56  77  41
  63  95  57  54  67  43  55 100  62  68  63  77  56  85  74  78  60  67
  79  69  68  67  62  54  93  64  67  80  34  62  86  65  53  54  59  70
  55  50  66  53  64  73  51  82  79  80  69  76  73  77  60  80  42  72
  85  97  74  49  62  47  89  48 100  68  55  45  76  91  62  91  38  65
  85  76  90  74  84  61  91  83  66  72  70  67  68  56  61  46  54  71
  56  74  57  82  76  70  90  90  68  66  52  76  68  72  82  92  54  92
  54  80  66  54  77  87  73  43  52  62  94  85  84  73  78  79  52  84
  57  50  49  59  60  43  47  70  73  53  58  94  68  83  58  62  71  86
  68  80  79  89  66  80  97  64  64  69  65  88  50  64  40  33  79  66
  70  62  79  74  92  80  46  45 100  78  47  67  70  92  56  64  71  53
  52  89  58  68  96  80  78  80  77  76  73  62  65  65  54  50  64  73
  99  72  15  48  73  81  63  30  80  51  90  62  82  54  62  65  63  66
  91  74  93  72  38  83  84  68  54  56  52  86  62  99  63  46  46  55
  70  65  81  85  80  64  81  88  74  73  51  90  79  80  60  81  65  68
  55  81  53  76  98  74  79  67  64  61  58  85  73  63  69  67  63  60
  71  87  61  77  68  50  76  84  78  66  76  76  78  60  74  60  54  44
  68 100  68  73  44  83  53  78  81  73  56  86  90  70  79  59  82  72
  87  67  64  65  36  52  79  58  90  85  99  84  74  87  72  99  74  80
  70  59  88  42  41  71  77  57  84  37  80  43  94  44  57  59  84  73
  73  55  72  56  82  72  47  74  71  68  59  86  68  65  75  85  53  92
  52  72  65  77  64  54  86  63  59  72  77  60  75  57  49  74  72  79
  60  55  70  43  82  82  57  84  82  62  79  44  77  32  61  61  60  70
  69  77  51  73  70  81  54  57  68  73  95  87  78  74  75  40  69  51
  36  49  67  76  83  87  64  76  68  88  92  93  51  82  52  58  70  76
  81  53  57  89  58  89  45  74  57  79  53  73  46  51  36  76  64  84
  85  50  68  69  67  63  93  61  55  96  65  81  46  72  53  87  38  80
  91  88  52  41  72  51  47  76  78  82  61  66  84  54  80  74  66  70
  71  44  54  80  95  59  74  48  91  85  73  75  69  38  27  79  63  82

In [10]:
for label, col in df[['gender', 'math score']].items():
    print(label, col.values)

gender ['female' 'female' 'female' 'male' 'male' 'female' 'female' 'male' 'male'
 'female' 'male' 'male' 'female' 'male' 'female' 'female' 'male' 'female'
 'male' 'female' 'male' 'female' 'male' 'female' 'male' 'male' 'male'
 'female' 'male' 'female' 'female' 'female' 'female' 'male' 'male' 'male'
 'female' 'female' 'female' 'male' 'male' 'female' 'female' 'male'
 'female' 'male' 'female' 'female' 'female' 'male' 'male' 'male' 'male'
 'male' 'female' 'female' 'female' 'male' 'male' 'female' 'male' 'male'
 'male' 'female' 'female' 'male' 'male' 'female' 'male' 'female' 'female'
 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'female' 'female'
 'female' 'male' 'male' 'male' 'male' 'female' 'female' 'female' 'female'
 'female' 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'female'
 'female' 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'female'
 'male' 'female' 'female' 'female' 'male' 'male' 'female' 'female' 'male'
 'female' 'female' 'female' 'female' 'female' 'male' 'female' 'male'
 'male' 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'male'
 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'female' 'female'
 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'male'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'male'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'female'
 'female' 'male' 'male' 'female' 'female' 'female' 'female' 'female'
 'female' 'female' 'female' 'male' 'female' 'female' 'female' 'male'
 'male' 'male' 'male' 'male' 'female' 'female' 'male' 'female' 'male'
 'female' 'male' 'male' 'male' 'female' 'female' 'female' 'female' 'male'
 'female' 'male' 'male' 'male' 'male' 'female' 'female' 'male' 'male'
 'female' 'male' 'male' 'male' 'female' 'female' 'male' 'male' 'female'
 'male' 'female' 'male' 'female' 'female' 'female' 'male' 'male' 'female'
 'male' 'male' 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'male'
 'male' 'female' 'female' 'male' 'male' 'male' 'male' 'female' 'female'
 'male' 'male' 'female' 'female' 'male' 'male' 'female' 'female' 'male'
 'female' 'female' 'female' 'male' 'female' 'female' 'male' 'male'
 'female' 'female' 'female' 'female' 'male' 'male' 'female' 'female'
 'male' 'male' 'female' 'female' 'female' 'male' 'male' 'male' 'female'
 'female' 'female' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'male'
 'female' 'male' 'female' 'male' 'male' 'male' 'female' 'female' 'female'
 'male' 'male' 'female' 'female' 'male' 'female' 'male' 'male' 'female'
 'female' 'female' 'female' 'female' 'female' 'female' 'male' 'male'
 'male' 'female' 'male' 'male' 'male' 'male' 'female' 'female' 'male'
 'male' 'female' 'female' 'male' 'female' 'female' 'male' 'male' 'female'
 'male' 'female' 'male' 'male' 'female' 'male' 'female' 'female' 'female'
 'female' 'male' 'female' 'male' 'female' 'female' 'male' 'female'
 'female' 'male' 'male' 'male' 'male' 'female' 'female' 'male' 'female'
 'male' 'female' 'female' 'male' 'female' 'female' 'female' 'male'
 'female' 'male' 'male' 'female' 'female' 'female' 'female' 'female'
 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'female'
 'female' 'male' 'male' 'female' 'male' 'female' 'female' 'female'
 'female' 'male' 'female' 'female' 'male' 'female' 'male' 'male' 'male'
 'female' 'male' 'male' 'male' 'male' 'male' 'female' 'female' 'female'
 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'female'
 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'female'
 'female' 'female' 'female' 'male' 'female' 'male' 'male' 'male' 'male'
 'female' 'female' 'female' 'male' 'female' 'male' 'female' 'male'
 'female' 'male' 'male' 'male' 'female' 'female' 'male' 'female' 'female'
 'male' 'female' 'male' 'female' 'female' 'female' 'female' 'female'
 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'male'
 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'female' 'female'
 'female' 'female' 'male' 'female' 'female' 'female' 'male' 'female'
 'female' 'male' 'female' 'female' 'female' 'male' 'male' 'male' 'female'
 'male' 'male' 'male' 'female' 'female' 'female' 'female' 'female'
 'female' 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'male'
 'female' 'female' 'female' 'female' 'female' 'male' 'female' 'male'
 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'female' 'female'
 'female' 'male' 'female' 'male' 'female' 'male' 'male' 'male' 'female'
 'male' 'male' 'female' 'female' 'male' 'female' 'male' 'female' 'female'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'male' 'male'
 'male' 'female' 'female' 'female' 'male' 'male' 'female' 'female'
 'female' 'female' 'female' 'female' 'female' 'female' 'female' 'female'
 'female' 'female' 'female' 'male' 'male' 'male' 'female' 'female'
 'female' 'male' 'male' 'female' 'female' 'female' 'female' 'female'
 'male' 'male' 'male' 'female' 'female' 'female' 'female' 'male' 'female'
 'male' 'female' 'female' 'female' 'female' 'male' 'male' 'male' 'female'
 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male' 'female' 'male'
 'male' 'female' 'female' 'male' 'male' 'female' 'female' 'male' 'female'
 'male' 'female' 'female' 'female' 'male' 'female' 'female' 'female'
 'female' 'female' 'male' 'female' 'female' 'female' 'female' 'female'
 'male' 'male' 'female' 'male' 'male' 'male' 'female' 'female' 'male'
 'female' 'female' 'female' 'male' 'male' 'female' 'male' 'female'
 'female' 'female' 'female' 'female' 'female' 'male' 'male' 'female'
 'male' 'male' 'female' 'male' 'female' 'male' 'male' 'male' 'male'
 'female' 'female' 'female' 'female' 'female' 'female' 'female' 'female'
 'female' 'male' 'female' 'female' 'male' 'female' 'female' 'male' 'male'
 'male' 'male' 'female' 'male' 'female' 'female' 'male' 'female' 'female'
 'male' 'female' 'female' 'male' 'female' 'male' 'female' 'male' 'male'
 'male' 'female' 'male' 'female' 'male' 'female' 'male' 'female' 'male'
 'female' 'male' 'male' 'female' 'male' 'male' 'male' 'female' 'female'
 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'female' 'male' 'female' 'male' 'male' 'female' 'male' 'female' 'female'
 'male' 'female' 'male' 'female' 'female' 'male' 'female' 'male' 'male'
 'male' 'female' 'female' 'male' 'female' 'female' 'female' 'female'
 'male' 'female' 'female' 'female' 'female' 'male' 'female' 'female'
 'female' 'male' 'female' 'female' 'female' 'male' 'male' 'female'
 'female' 'male' 'female' 'male' 'female' 'male' 'male' 'female' 'female'
 'female' 'male' 'female' 'female' 'male' 'male' 'male' 'male' 'female'
 'male' 'female' 'male' 'female' 'male' 'female' 'female' 'female'
 'female' 'male' 'female' 'female' 'male' 'female' 'female' 'female'
 'male' 'female' 'female' 'male' 'female' 'male' 'female' 'male' 'female'
 'male' 'female' 'female' 'male' 'female' 'male' 'female' 'male' 'male'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'male' 'female'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'male'
 'male' 'male' 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'female'
 'male' 'male' 'male' 'female' 'female' 'male' 'female' 'female' 'male'
 'female' 'female' 'female' 'male' 'female' 'male' 'female' 'female'
 'female' 'male' 'female' 'female' 'male' 'female' 'male' 'female' 'male'
 'female' 'female' 'female' 'female' 'male' 'male' 'female' 'female'
 'male' 'male' 'female' 'female' 'female' 'female' 'female' 'male'
 'female' 'female' 'male' 'male' 'female' 'male' 'female' 'male' 'male'
 'male' 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'male'
 'male' 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'female'
 'female' 'male' 'female' 'male' 'female' 'male' 'female' 'female' 'male'
 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'female'
 'female' 'female' 'male' 'female' 'male' 'male' 'female' 'female'
 'female' 'male' 'female' 'female' 'female' 'female' 'male' 'male' 'male'
 'female' 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'male'
 'female' 'female' 'male' 'female' 'female' 'female' 'male' 'female'
 'male' 'female' 'female' 'female']
math score [ 72  69  90  47  76  71  88  40  64  38  58  40  65  78  50  69  88  18
  46  54  66  65  44  69  74  73  69  67  70  62  69  63  56  40  97  81
  74  50  75  57  55  58  53  59  50  65  55  66  57  82  53  77  53  88
  71  33  82  52  58   0  79  39  62  69  59  67  45  60  61  39  58  63
  41  61  49  44  30  80  61  62  47  49  50  72  42  73  76  71  58  73
  65  27  71  43  79  78  65  63  58  65  79  68  85  60  98  58  87  66
  52  70  77  62  54  51  99  84  75  78  51  55  79  91  88  63  83  87
  72  65  82  51  89  53  87  75  74  58  51  70  59  71  76  59  42  57
  88  22  88  73  68 100  62  77  59  54  62  70  66  60  61  66  82  75
  49  52  81  96  53  58  68  67  72  94  79  63  43  81  46  71  52  97
  62  46  50  65  45  65  80  62  48  77  66  76  62  77  69  61  59  55
  45  78  67  65  69  57  59  74  82  81  74  58  80  35  42  60  87  84
  83  34  66  61  56  87  55  86  52  45  72  57  68  88  76  46  67  92
  83  80  63  64  54  84  73  80  56  59  75  85  89  58  65  68  47  71
  60  80  54  62  64  78  70  65  64  79  44  99  76  59  63  69  88  71
  69  58  47  65  88  83  85  59  65  73  53  45  73  70  37  81  97  67
  88  77  76  86  63  65  78  67  46  71  40  90  81  56  67  80  74  69
  99  51  53  49  73  66  67  68  59  71  77  83  63  56  67  75  71  43
  41  82  61  28  82  41  71  47  62  90  83  61  76  49  24  35  58  61
  69  67  79  72  62  77  75  87  52  66  63  46  59  61  63  42  59  80
  58  85  52  27  59  49  69  61  44  73  84  45  74  82  59  46  80  85
  71  66  80  87  79  38  38  67  64  57  62  73  73  77  76  57  65  48
  50  85  74  60  59  53  49  88  54  63  65  82  52  87  70  84  71  63
  51  84  71  74  68  57  82  57  47  59  41  62  86  69  65  68  64  61
  61  47  73  50  75  75  70  89  67  78  59  73  79  67  69  86  47  81
  64 100  65  65  53  37  79  53 100  72  53  54  71  77  75  84  26  72
  77  91  83  63  68  59  90  71  76  80  55  76  73  52  68  59  49  70
  61  60  64  79  65  64  83  81  54  68  54  59  66  76  74  94  63  95
  40  82  68  55  79  86  76  64  62  54  77  76  74  66  66  67  71  91
  69  54  53  68  56  36  29  62  68  47  62  79  73  66  51  51  85  97
  75  79  81  82  64  78  92  72  62  79  79  87  40  77  53  32  55  61
  53  73  74  63  96  63  48  48  92  61  63  68  71  91  53  50  74  40
  61  81  48  53  81  77  63  73  69  65  55  44  54  48  58  71  68  74
  92  56  30  53  69  65  54  29  76  60  84  75  85  40  61  58  69  58
  94  65  82  60  37  88  95  65  35  62  58 100  61 100  69  61  49  44
  67  79  66  75  84  71  67  80  86  76  41  74  72  74  70  65  59  64
  50  69  51  68  85  65  73  62  77  69  43  90  74  73  55  65  80  50
  63  77  73  81  66  52  69  65  69  50  73  70  81  63  67  60  62  29
  62  94  85  77  53  93  49  73  66  77  49  79  75  59  57  66  79  57
  87  63  59  62  46  66  89  42  93  80  98  81  60  76  73  96  76  91
  62  55  74  50  47  81  65  68  73  53  68  55  87  55  53  67  92  53
  81  61  80  37  81  59  55  72  69  69  50  87  71  68  79  77  58  84
  55  70  52  69  53  48  78  62  60  74  58  76  68  58  52  75  52  62
  66  49  66  35  72  94  46  77  76  52  91  32  72  19  68  52  48  60
  66  89  42  57  70  70  69  52  67  76  87  82  73  75  64  41  90  59
  51  45  54  87  72  94  45  61  60  77  85  78  49  71  48  62  56  65
  69  68  61  74  64  77  58  60  73  75  58  66  39  64  23  74  40  90
  91  64  59  80  71  61  87  82  62  97  75  65  52  87  53  81  39  71
  97  82  59  61  78  49  59  70  82  90  43  80  81  57  59  64  63  71
  64  55  51  62  93  54  69  44  86  85  50  88  59  32  36  63  67  65
  85  73  34  93  67  88  57  79  67  70  50  69  52  47  46  68 100  44
  57  91  69  35  72  54  74  74  64  65  46  48  67  62  61  70  98  70
  67  57  85  77  72  78  81  61  58  54  82  49  49  57  94  75  74  58
  62  72  84  92  45  75  56  48 100  65  72  62  66  63  68  75  89  78
  53  49  54  64  60  62  55  91   8  81  79  78  74  57  40  81  44  67
  86  65  55  62  63  88  62  59  68  77]

In [11]:
result = df.loc[2:5, ['gender','math score']]
print(result)
print("----------------------")
for index, row in result.iterrows():
    print(index, row['gender'], row['math score'])

   gender  math score
2  female          90
3    male          47
4    male          76
5  female          71
----------------------
2 female 90
3 male 47
4 male 76
5 female 71

In [12]:
for index, row in result.iterrows():
    print(index, row.values)

2 ['female' 90]
3 ['male' 47]
4 ['male' 76]
5 ['female' 71]